{
  TFile *file = TFile::Open("../../root_files/nutples/hist_notriggernoht.root"); 
  TH1F *promptel = (TH1F*)file->FindObjectAny("isopromptel");
  TH1F *promptmu = (TH1F*)file->FindObjectAny("isopromptmu");
  TH1F *hfmu = (TH1F*)file->FindObjectAny("isohfmu");
  TH1F *hfel = (TH1F*)file->FindObjectAny("isohfel");
  TH1F *fakemu = (TH1F*)file->FindObjectAny("isofakemu");
  TH1F *fakeel = (TH1F*)file->FindObjectAny("isofakeel");
  TCanvas *c1 = new TCanvas("c1","c1",1301,333,620,544);
  gStyle->SetOptStat(0);
  gStyle->SetOptTitle(0);
  gStyle->SetPalette(1);
  c1->Range(-0.125,-0.125,1.125,1.125);
  c1->SetFillColor(0);
  c1->SetBorderSize(0);
  c1->SetTickx(1);
  c1->SetTicky(1);
  c1->SetFrameFillColor(0);
  c1->SetFrameBorderMode(0);
  promptel->SetLineColor(3);
  promptel->GetXaxis()->SetTitle("Electrons Relative Isolation");
  promptel->GetXaxis()->SetLabelFont(42);
  promptel->GetXaxis()->SetTitleFont(42);
  promptel->GetYaxis()->SetTitle("Distribution normalized to 1");
  promptel->GetYaxis()->SetLabelFont(42);
  promptel->GetYaxis()->SetTitleFont(42);
  promptel->DrawNormalized();
  hfel->SetLineColor(2);
  hfel->DrawNormalized("SAME");
  fakeel->SetLineColor(4);
  fakeel->DrawNormalized("SAME");
  TCanvas *c2 = new TCanvas("c2","c2",1301,333,620,544);
  c2->Range(-0.125,-0.125,1.125,1.125);
  c2->SetFillColor(0);
  c2->SetBorderSize(0);
  c2->SetTickx(1);
  c2->SetTicky(1);
  c2->SetFrameFillColor(0);
  c2->SetFrameBorderMode(0);
  promptmu->SetLineColor(3);
  promptmu->GetXaxis()->SetTitle("Muons Relative Isolation");
  promptmu->GetXaxis()->SetLabelFont(42);
  promptmu->GetXaxis()->SetTitleFont(42);
  promptmu->GetYaxis()->SetTitle("Distribution normalized to 1");
  promptmu->GetYaxis()->SetLabelFont(42);
  promptmu->GetYaxis()->SetTitleFont(42);
  promptmu->DrawNormalized();
  hfmu->SetLineColor(2);
  hfmu->DrawNormalized("SAME");
  fakemu->SetLineColor(4);
  fakemu->DrawNormalized("SAME");
}
