{
  gStyle->SetPalette(1);
  TFile *f1 = TFile::Open("../../root/OUT/Salida_LM0_temp.root");
  TFolder *fol1 = (TFolder*)f1->Get("HT");
  TH2D *h1;
  h1 = (TH2D*)fol1->FindObjectAny("PFHT_vs_MET");
  TCanvas *c1 = new TCanvas();
  //  gStyle->SetOptStat(1110);
  gStyle->SetOptStat(0);
  gStyle->SetOptTitle(0);
  //gStyle->SetFillColor(0);
  gStyle->SetPadTickX(1);
  gStyle->SetPadTickY(1);
  c1->SetFillColor(0);
  h1->GetXaxis()->SetLabelFont(42);
  h1->GetXaxis()->SetTitleFont(42);
  h1->GetXaxis()->SetTitle("PF HT (GeV)");
  h1->GetYaxis()->SetLabelFont(42);
  h1->GetYaxis()->SetTitleFont(42);
  h1->GetYaxis()->SetTitle("PF MET");
  h1->GetZaxis()->SetLabelFont(42);
  h1->GetZaxis()->SetTitleFont(42);
  h1->GetZaxis()->SetTitle("N. Entries/ 34 pb^{-1}");
  h1->SetContour(99);
  h1->GetXaxis()->SetRangeUser(80,1000);
  h1->GetYaxis()->SetRangeUser(20,500);
  c1->SetRightMargin(0.2);
  h1->Draw("COLZ");
  TLine *l = new TLine(300,20,301,500);
  l->SetLineColor(1);
  l->SetLineWidth(3);
  l->Draw("SAME");
  TLine *l1 = new TLine(80,50,1000,50);
  l1->SetLineColor(1);
  l1->SetLineWidth(3);
  l1->Draw("SAME");
  c1->SaveAs("LM0_PFHT_vs_PFMET.jpg");
  cout << h1->GetYaxis()->GetNbins() << endl;
  cout << h1->Integral(30,100,5,50) << endl;
}
