#!/bin/tcsh -x

source $VO_CMS_SW_DIR/cmsset_default.csh
source /afs/cern.ch/cms/caf/setup.csh

set me = `whoami`

cd /tmp/${me}/
mkdir ----RUN-NUMBER----
cd ----RUN-NUMBER----
project CMSSW
cmsrel ----RELEASE----
cd ----RELEASE----/src

eval `scramv1 runtime -csh`
mkdir UserCode/
cd UserCode/
mkdir OIorio/
cd ..
cvs co UserCode/OIorio/L1Trigger
cd UserCode/OIorio/
cp -r L1Trigger/ ..
cd ..
cd L1Trigger/
scram b 

cd /tmp/${me}/----RUN-NUMBER----/----RELEASE----/src
cp $HOME/scratch0/----RUN-NUMBER----/python/----input_file---- /tmp/${me}/----RUN-NUMBER----/----RELEASE----/src

EdmPluginRefresh

rm ----input_file----.out
cmsRun ----input_file---- > ----input_file----.out
cmsStageOut ----input_file----.out /store/caf/user/ccmuon/RPC/GlobalRuns/----DATASET----/----RUN-NUMBER----/out/
cmsStageOut ----output_file---- /store/caf/user/ccmuon/RPC/GlobalRuns/----DATASET----/----RUN-NUMBER----/root/
rfchmod +777 /castor/cern.ch/cms/store/caf/user/ccmuon/RPC/GlobalRuns/----DATASET----/----RUN-NUMBER----/root/----output_file----

exit 0
